/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e225710;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class compare {
    @Test
    void compareTest() {
        number number = new number();
        number.set_number();
        int[] arr = number.return_number();
        String[] strarr = {"1", "2", "3"};
        compare_machine cm = new compare_machine(strarr, arr);
        cm.compare();
        if(cm.Ball + cm.Strike > 3){
            fail();
        }
    }
}
