/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e225710;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class numberTest {
    @Test void duplicatenumberText(){
        number number = new number();
        number.set_number();
        int[] arr = number.return_number();
        int first = arr[0];
        int second = arr[1];
        int third = arr[2];
        if(first == second){
            fail();
        }
        if(second == third){
            fail();
        }
        if(third == first){
            fail();
        }
    }    
}
